name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run lint-check

  check_formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run format-check

  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run compile

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run test
        env:
          LFM_API_KEY: ${{ secrets.LFM_API_KEY }}
          LFM_API_CLIENT_ID: ${{ secrets.LFM_API_CLIENT_ID }}
          LFM_API_CLIENT_SECRET: ${{ secrets.LFM_API_CLIENT_SECRET }}
          LFM_API_AUTH_HOST: auth.lfmdev.in
          LFM_API_HOST: api.lfmdev.in
